
// 用户登录
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAIT = 'LOGIN_FAIT';

export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIT = 'COURSE_LIST_FAIT'

export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIT = 'COURSE_DETAILS_FAIT'

export const COURSE_CATALOG_SUCCESS = 'COURSE_CATALOG_SUCCESS'
export const COURSE_CATALOG_FAIT = 'COURSE_CATALOG_FAIT'
